export default {
	/*mySidebar: [
		{
			type: 'autogenerated',
			dirName: '.', // generate sidebar from the docs folder (or versioned_docs/<version>)
		},
	],*/
	mySidebar: [
		{
			type: 'doc',
			label: 'Start Here',
			id: 'helpful-links',
		},
		{
			type: 'category',
			label: 'Lesson Plans',
			items: [
				{
					type: 'category',
					label: 'PPL/CPL',
					link: {type: 'doc', id: 'Lesson-Plans/index'},
					items: ['Lesson-Plans/Human Factors', 'Lesson-Plans/Visual Scanning', 'Lesson-Plans/Runway Incursion Avoidance', 'Lesson-Plans/Airplane Aerodynamics and Performance', 'Lesson-Plans/Airplane Flight Controls', 'Lesson-Plans/Aircraft Systems', 'Lesson-Plans/National Airspace System', 'Lesson-Plans/Navigation and Flight Planning', 'Lesson-Plans/Night Operations', 'Lesson-Plans/High Altitude', 'Lesson-Plans/Pilot Qualifications', 'Lesson-Plans/Airworthiness Requirements', 'Lesson-Plans/Weather', 'Lesson-Plans/Maneuvers', 'Lesson-Plans/Communications, Light Signals, and Runway Lighting Systems', 'Lesson-Plans/Traffic Patterns'],
				},
				{
					type: 'category',
					label: 'Instrument',
					link: {type: 'doc', id: 'Lesson-Plans/instrumentIndex'},
					items: ['Lesson-Plans/Human Factors','Lesson-Plans/Pilot Qualifications IFR','Lesson-Plans/Cross Country Flight Planning IFR','Lesson-Plans/Tracking:Intercepting and DME Arcs', 'Lesson-Plans/Holding Procedures','Lesson-Plans/Approaches','Lesson-Plans/Weather'],
				},
			],

		},
		{
			type: 'category',
			label: 'References',
			link: {type: 'doc', id: 'References/referencesIndex'},
			items: ['References/Airspace', 'References/fars','References/RadioCalls', 'References/StudentExpectations', 'References/WeightBalance'],
		},
		],
};

